title: Learning Socially Appropriate Navigation
description: Project page for our RAL 2025 paper on preference-based socially aware robot navigation.
author: Tribhi Kathuria
email: tribhi@umich.edu

# GitHub Pages theme
theme: jekyll-theme-minimal

# Optional: Repository details if hosting under /project-name/
# Uncomment and set if your site is at username.github.io/project-name/
# baseurl: "/Door-Nav"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Social / metadata
url: "https://tribhi.github.io"
github_username: tribhi
